model:
  class_path: terragpu.ai.deep_learning.models.unet_model.UNetSegmentation
  init_args:
    input_channels: 4
    num_classes: 2
    num_layers: 5
    features_start: 64
    bilinear: false
data:
  class_path: terragpu.ai.deep_learning.datamodules.segmentation_datamodule.SegmentationDataModule
  init_args:
    dataset_dir: '/Users/jacaraba/Desktop/development/ilab/vhr-cloudmask/data/dataset'
    images_regex: '/Users/jacaraba/Desktop/development/ilab/vhr-cloudmask/data/images/*tif'
    labels_regex: '/Users/jacaraba/Desktop/development/ilab/vhr-cloudmask/data/labels/*tif'
    generate_dataset: true
    tile_size: 64
    max_patches: 100
    augment: true
    chunks:
      band: 1
      x: 2048
      y: 2048
    input_bands:
    - CB
    - B
    - G
    - Y
    - R
    - RE
    - N1
    - N2
    output_bands:
    - B
    - G
    - R
    - N1
    seed: 24
    normalize: true
    pytorch: true
    val_split: 0.2
    test_split: 0.1
    num_workers: 12
    batch_size: 16
    shuffle: true
    pin_memory: true
    drop_last: false
    raster_regex: rasters/*.tif
seed_everything: null
trainer:
  logger: true
  checkpoint_callback: null
  enable_checkpointing: true
  # callbacks: null
  default_root_dir: output_model
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: auto
  gpus: null
  auto_select_gpus: true
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 10
  min_epochs: 1
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  accelerator: auto
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: true
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
ckpt_path: null
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0001
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.1