FROM nasanccs/pytorch-caney:latest
LABEL maintainer="glenn.s.tamkin@nasa.gov"

ENV TFC_VERSION=0.1.1
ENV VHR_CLOUDMASK_VERSION=main

RUN pip install hydra-core

RUN pip install git+https://github.com/dshean/pygeotools.git@master

HEALTHCHECK NONE
ENTRYPOINT [""]
