experiment_name: vietnam-clouds
seed: 42
gpu_devices: 0,1,2,3
mixed_precision: False
xla: False

dataset_csv: ../config/config_clouds/vietnam_clouds.csv
data_dir: /lscratch/jacaraba/vietnam-lcluc/clouds

input_bands:
  - CoastalBlue
  - Blue
  - Green
  - Yellow
  - Red
  - RedEdge
  - NIR1
  - NIR2

output_bands:
  - Blue
  - Green
  - Red
  - NIR1

tile_size: 256
include_classes: False
augment: True
batch_size: 128
n_classes: 1
test_size: 0.20
learning_rate: 0.0001
max_epochs: 6000

model_filename: /lscratch/jacaraba/vietnam-lcluc/clouds/model/23-0.05.hdf5
#inference_regex: '/att/pubrepo/ILAB/projects/Vietnam/Sarah/data/*.tif'
#inference_regex: '/att/pubrepo/ILAB/projects/Vietnam/Sarah/data/Keelin11_20151203_data.tif'
#inference_regex: '/att/gpfsfs/briskfs01/ppl/mwooten3/Vietnam_LCLUC/TOA/M1BS/pansharpen_TamNongClip/*.tif'
# trouble -- inference_regex: '/att/gpfsfs/briskfs01/ppl/mwooten3/Vietnam_LCLUC/TOA/M1BS/pansharpen_TamNongClip/WV02_20110408_M1BS_103001000A5FE000-toa_pansharpen_clip.tif'
#inference_regex: '/att/gpfsfs/briskfs01/ppl/mwooten3/Vietnam_LCLUC/TOA/M1BS/pansharpen_TamNongClip/WV02_20120130_M1BS_1030010011A30B00-toa_pansharpen_clip.tif'
#inference_regex: '/att/gpfsfs/briskfs01/ppl/mwooten3/Vietnam_LCLUC/TOA/M1BS/pansharpen_TamNongClip/WV02_20130125_M1BS_103001001DD53500-toa_pansharpen_clip.tif'
#inference_regex: '/att/nobackup/mcarrol2/LCLUC_Senegal/ForKonrad/*data.tif'
inference_regex: '/adapt/nobackup/projects/ilab/projects/Senegal/Tapan_data/*.tif'
inference_save_dir: /adapt/nobackup/projects/ilab/projects/Vietnam/Jordan/vhr-cloudmask-data/vietnam/results_mosaic
window_size: 8192
