name: Check Disk Space 
on: workflow_dispatch

jobs:
  check-disk-space:
    runs-on: ubuntu-latest
    steps:
        
    - name: check disk space 
      run: |
        df -h
        df -hi
        ls -alRt /home/runner/runners/
        du -s /home/runner/runners/*
